#!/bin/bash

# touch /home/mashrit/Documents/scratchpad-temp

case $1 in 
	"clear")
		rm "/tmp/scratchpad-closed"
		pkill scratchpadd
		exit 0
	;;
esac

if !(pgrep cm); then
	kitty -T cm -e cm &
	rm "/tmp/scratchpad-closed"
	exit 1
fi

id=$(niri msg -j windows | jq '.[] | select(.title == "cm")' | jq .id)

workId=$(niri msg -j workspaces | jq '.[] | select(.is_focused == true)' | jq .idx)
currId=$(niri msg -j windows | jq '.[] | select(.is_focused == true)' | jq .id)
emptyWorkId=$(niri msg -j workspaces | jq '.[] | select(.active_window_id == null)' | jq .idx)

# notify-send "id is $id, curr id is $currId"

if  [ $currId == $id ]; then
	niri msg action move-window-to-floating --id $id
	niri msg action focus-window-previous
	niri msg action set-window-width --id $id 0
	niri msg action set-window-height --id $id 0
	niri msg action move-floating-window --id $id -x 0 -y 0
	sleep 0.1
	niri msg action move-window-to-workspace --window-id $id $emptyWorkId
	touch "/tmp/scratchpad-closed"
	# echo -e "$emptyWorkId\ntrue" > /home/mashrit/Documents/scratchpad-temp

	if !(pgrep scratchpadd); then
		scratchpadd
	fi
else
	rm "/tmp/scratchpad-closed"
	niri msg action move-window-to-floating --id $id
	niri msg action move-window-to-workspace --window-id $id $workId
	niri msg action focus-window --id $id 
	niri msg action move-floating-window -x 32 -y 16
	niri msg action set-window-height --id $id 480
	niri msg action set-window-width --id $id 640
	# echo -e "$emptyWorkId\nfalse" > /home/mashrit/Documents/scratchpad-temp
fi

